server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://mysql-1.cbw4aciueih6.sa-east-1.rds.amazonaws.com:3306/teste-pg-xpe
    username: admin
    password: dVRJe2KyZF3rfAT
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

springdoc:
  packages-to-scan: br.com.rjfpinformatica